---
abstract: 'Use CPAN::Mini::Webserver as a PSGI application'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Compress::Zlib: 2.033
  File::Path: 2.08
  File::Slurp: 9999.16
  HTTP::Request::Common: 6.00
  Module::Build: 0.3601
  Plack::Test: 0
  Test::Builder: 0.98
  URI: 1.58
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200005, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Webserver-PSGI
requires:
  CGI: 3.53
  CGI::Emulate::PSGI: 0.11
  CPAN::Mini::Webserver: 0.51
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=CPAN-Mini-Webserver-PSGI
version: 0.01
